<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="mrs" nsURI="http://www.example.org/mrs" nsPrefix="mrs">
  <eClassifiers xsi:type="ecore:EClass" name="ModularReferenceStructure">
    <eStructuralFeatures xsi:type="ecore:EReference" name="layers" lowerBound="1"
        upperBound="-1" eType="#//Layer" containment="true" eOpposite="#//Layer/modularReferenceStructure"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="loadedProfiles" upperBound="-1"
        eType="ecore:EClass ../../org.modelversioning.emfprofile/model/emfprofiles.ecore#//Profile"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Layer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="metamodels" upperBound="-1"
        eType="#//Metamodel" containment="true" eOpposite="#//Metamodel/layer"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="modularReferenceStructure"
        lowerBound="1" eType="#//ModularReferenceStructure" eOpposite="#//ModularReferenceStructure/layers"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Metamodel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="mainPackage" lowerBound="1"
        eType="ecore:EClass ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EPackage"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="layer" lowerBound="1" eType="#//Layer"
        eOpposite="#//Layer/metamodels"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"
        defaultValueLiteral="aMetamodel"/>
  </eClassifiers>
</ecore:EPackage>
